name: Trigger Remote Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo B workflow
        run: |
          curl -v -i -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer YOUR_PAT" \
  https://api.github.com/repos/SANTOSH146/Repo-B/dispatches \
  -d '{"event_type":"run-from-repoA","client_payload":{"env":"dev","branch":"main"}}'

